name: Ежедневное напоминание о Турции
env:
  TZ: Europe/Moscow

on:
  schedule:
    - cron: '0 7 * * *'  # 15:55 МСК = 12:55 UTC
  workflow_dispatch: # Возможность запуска вручную

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Вызов Vercel API
    steps:
      - name: Запрос к Vercel API
        run: |
          curl -v "https://schedular-vacating-hj8fcq7ba-nickkkis-projects.vercel.app/api/countdown"
